#!/usr/bin/env node

"use strict"

const fs = require('fs');
const yaml = require("yamljs");
//const dateFormat = require('dateformat');
const request = require('request-promise');

const C = yaml.load("config.yaml");

const runNodeSchedule = C.runNodeSchedule;
const priceCurrency = C.priceCurrency;
const priceRegion = C.priceRegion;
const scheduleHours = C.scheduleHours;
const scheduleMinutes = C.scheduleMinutes;

let schedule;
let runSchedule;
if (runNodeSchedule) {
  schedule = require('node-schedule');
  runSchedule = new schedule.RecurrenceRule();
  runSchedule.hour = scheduleHours;
  runSchedule.minute = scheduleMinutes;
}

let nordPool = {
    'uri': "https://www.nordpoolgroup.com/api/marketdata/page/10/" + priceCurrency + "/",
  headers: {
    'accept': 'application/json',
    'Content-Type': 'text/json',
  },
  json: true
  //method: 'GET'
};

const daysInMonth = [undefined, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

const computePrices = C.computePrices;
const supplierKwhPrice = C.supplierKwhPrice; //0.0277;
const supplierMonthPrice = C.supplierMonthPrice; // 9.0;
const supplierVatPercent = C.supplierVatPercent;  // 25 

const spotVatPercent = C.spotVatPercent;

const gridKwhPrice = C.gridKwhPrice; //0.4454;
const gridDayPrice = C.gridDayPrice; //6.66;
const gridVatPercent = C.gridVatPercent;

let oneDayPrices = [];

function addZero(num) {
  if (num <= 9) {
    return "0" + num;
  }
  return num;
}

function dayAhead() {
  let oneDay = 24 * 60 * 60 * 1000;
  let now = new Date();
  let tomorrow = new Date(now.getTime() + oneDay);
  let day = tomorrow.toLocaleDateString();
  let ret = day.split("-")[0]
    + "-" + addZero(day.split("-")[1])
    + "-" + addZero(day.split("-")[2]);
  return ret;
}

let getValues = async (data) => {
  let date = oneDayPrices[0].startTime.substr(0, 10) + ".json";
  //if (!fs.existsSync("./data/price-" + file)) {
  fs.writeFileSync("./data/prices-" + date, JSON.stringify(oneDayPrices, false, 2));
  //}
};

function computePrice(priceObj) {
  let month = priceObj.startTime.split("-")[1] * 1;
  let supplierPrice = supplierKwhPrice + supplierMonthPrice / daysInMonth[month] / 24;
  supplierPrice += supplierPrice  * supplierVatPercent / 100;
  supplierPrice += priceObj.price * 1 + priceObj.price * spotVatPercent / 100;
  let gridPrice = gridKwhPrice + gridDayPrice / 24;
  gridPrice += gridDayPrice * gridVatPercent / 100;
  return {
    startTime: priceObj.startTime,
    endTime: priceObj.endTime,
    spotPrice: priceObj.price * 1,
    customerPrice: (supplierPrice + gridPrice).toFixed(4) * 1
  }
}

function run() {
  if (!fs.existsSync("./data/prices-" + dayAhead() + ".json")) {
    request(nordPool)
      .then(function (body) {
        let rows = body.data.Rows;
        for (let i = 0; i < 24; i++) {
          let price = rows[i].Columns[priceRegion].Value;
          let priceObj = {
            startTime: rows[i].StartTime,
            endTime: rows[i].EndTime,
            price: ((price.split(",")[0] + "." + price.split(",")[1]) / 100).toFixed(4) * 1
          }
          if (computePrices)
            oneDayPrices.push(computePrice(priceObj));
          else
            oneDayPrices.push(priceObj);
        }
      })
      .catch(function (e) {
        console.log(e)
      })
      .then(getValues);
  }
}

if (runNodeSchedule) {
  let sched = schedule.scheduleJob(runSchedule, function() {
    run();
  })
} else
  run();
  
